import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CollectionStore } from '../../core/services/collection.store';
@Component({selector:'app-stats-page',changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <header><p class="eyebrow">ESTADÍSTICAS</p><h1>Tu progreso</h1><p>Una vista clara de lo que ya conseguiste y lo que falta.</p></header>
  <section class="summary"><article><span>Obtenidos</span><strong>{{store.ownedCount()}}</strong></article><article><span>Faltantes</span><strong>{{store.missingCount()}}</strong></article><article><span>Completado</span><strong>{{store.percent()}}%</strong></article></section>
  <section class="panel"><h2>Progreso por generación</h2>@for(item of store.groupProgress('generation');track item.label){<div class="row"><div><strong>{{item.label}}</strong><span>{{item.owned}} / {{item.total}}</span></div><progress [value]="item.owned" [max]="item.total"></progress><b>{{item.percent}}%</b></div>}</section>
  <section class="panel"><h2>Progreso por tipo</h2><div class="type-grid">@for(item of store.groupProgress('type');track item.label){<article><div><strong>{{item.label}}</strong><span>{{item.owned}} / {{item.total}}</span></div><progress [value]="item.owned" [max]="item.total"></progress><b>{{item.percent}}%</b></article>}</div></section>
`,styles:[`header h1{font-size:3.5rem;margin:4px 0}.eyebrow{color:var(--red);font-weight:900;letter-spacing:.2em}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:30px 0}.summary article,.panel{background:var(--surface);border:1px solid var(--line);border-radius:22px;padding:24px;box-shadow:var(--shadow)}.summary span,.row span,.type-grid span{display:block;color:var(--muted);font-size:.84rem}.summary strong{font-size:2.8rem}.panel{margin-top:20px}.row{display:grid;grid-template-columns:180px 1fr 55px;gap:16px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line)}progress{width:100%;height:12px;accent-color:var(--red)}.type-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.type-grid article{background:var(--surface-2);border-radius:15px;padding:16px}.type-grid b{float:right}@media(max-width:650px){.summary{grid-template-columns:1fr}.row{grid-template-columns:1fr}.row b{display:none}}`]})
export class StatsPage{readonly store=inject(CollectionStore);}
