import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CollectionStore } from '../../core/services/collection.store';
@Component({selector:'app-settings-page',imports:[FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<header><p>PERFIL Y RESPALDO</p><h1>Configuración</h1></header>
<section class="panel"><h2>Nombre del entrenador</h2><p>Se usará en las notificaciones cuando desbloquees una medalla.</p><div class="name-row"><input [ngModel]="name()" (ngModelChange)="name.set($event)" placeholder="Ej. Papoi"><button class="primary" (click)="saveName()">Guardar nombre</button></div>@if(message()){<p class="message">{{message()}}</p>}</section>
<section class="panel"><h2>Exportar colección</h2><p>Descarga un JSON con Pokémon obtenidos, favoritos, cartas específicas, cantidades, idiomas y configuración.</p><button class="primary" (click)="store.exportJson()">Exportar progreso</button></section>
<section class="panel"><h2>Importar colección</h2><p>Restaura un respaldo compatible. Los registros importados reemplazarán coincidencias locales.</p><label class="file">Seleccionar archivo JSON<input type="file" accept="application/json,.json" (change)="importFile($event)"></label></section>
<section class="panel"><h2>Actualizar datos</h2><p>Consulta PokéAPI y refresca nombres, tipos, generaciones e imágenes sin borrar tu progreso. También puedes actualizar el total global de cartas TCG para el logro final.</p><div class="actions"><button (click)="store.syncPokemon()" [disabled]="store.syncing()">{{store.syncing()?'Actualizando '+store.progress()+'%':'Actualizar Pokédex'}}</button><button (click)="store.refreshTcgTotal()">Actualizar total TCG</button></div><p class="message">Total TCG actual: {{store.totalTcgCards() || 'sin sincronizar'}}</p></section>
`,styles:[`header p{color:var(--red);font-weight:950;letter-spacing:.2em}header h1{font-size:clamp(2.6rem,8vw,4.5rem);margin:0 0 25px}.panel{background:var(--surface);border:1px solid var(--line);border-radius:22px;padding:25px;margin-bottom:16px;box-shadow:var(--shadow)}.panel p{color:var(--muted)}button,.file{display:inline-block;border:1px solid var(--line);background:var(--surface-2);color:var(--text);padding:12px 18px;border-radius:14px;font-weight:900;cursor:pointer}.primary{background:var(--red);color:white;border:0}.file input{display:none}.message{font-weight:800}.name-row,.actions{display:flex;gap:10px;flex-wrap:wrap}input{height:48px;min-width:260px;flex:1;border:1px solid var(--line);background:var(--surface-2);color:var(--text);border-radius:14px;padding:0 14px}@media(max-width:560px){.name-row,.actions{display:grid}input{min-width:0;width:100%}}`]})
export class SettingsPage{readonly store=inject(CollectionStore);readonly name=signal(this.store.trainerName());readonly message=signal('');async saveName(){await this.store.setTrainerName(this.name());this.message.set('Nombre guardado correctamente.');setTimeout(()=>this.message.set(''),2500);}async importFile(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{await this.store.importJson(file);this.name.set(this.store.trainerName());this.message.set('Respaldo importado correctamente.');}catch{this.message.set('El archivo no es un respaldo válido.');}finally{input.value='';}}}
